"""Golden tests for citation_formatter.py — independent expected strings.

All expected strings are hand-crafted per GB/T 7714-2015 rules,
NOT generated by the formatter under test.

Covers:
  - GB/T 7714 numeric (顺序编码制): 14 golden cases
  - GB/T 7714 author-date (著者-出版年): 2 golden cases
  - APA 7: basic checks
  - BibTeX & RIS: structure + DOI preservation
  - CSL-JSON: DOI / field mapping
  - Unsupported types
  - citeproc-py availability check
"""

from __future__ import annotations

import sys
from pathlib import Path

_TOOLS_DIR = Path(__file__).resolve().parent.parent
if not (_TOOLS_DIR / "scholarly").is_dir() and not (_TOOLS_DIR / "content_quality.py").exists():
    _TOOLS_DIR = _TOOLS_DIR / "tools"
if str(_TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(_TOOLS_DIR))

import pytest

from scholarly.citation_formatter import (
    APA7FallbackFormatter,
    CitationFormatter,
    CitationFormatterError,
    GBT7714FallbackFormatter,
    HAS_CITEPROC,
    CITEPROC_VERSION,
    export_bibtex,
    export_ris,
    to_csl_json,
)
from scholarly.models import (
    CitationData,
    CitationEngine,
    CitationStyle,
    ScholarlyRecord,
    SourceStatus,
)


# ═══════════════════════════════════════════════════════════
# Fixtures — independently constructed, NOT derived from formatter
# ═══════════════════════════════════════════════════════════

@pytest.fixture
def record_cn_single():
    """中文期刊文章，单作者"""
    return ScholarlyRecord(
        doi="10.1234/test.1",
        title="平台治理中的算法权力研究",
        authors=[{"family": "张", "given": "三"}],
        journal_name="新闻与传播研究",
        year=2025,
        volume="32",
        issue="4",
        page="15-28",
        issn=["1005-2577"],
        pub_type="article-journal",
    )


@pytest.fixture
def record_cn_three_authors():
    """中文期刊文章，三位作者（≤3，全部照录）"""
    return ScholarlyRecord(
        doi="10.1234/test.2",
        title="深度学习在自然语言处理中的应用",
        authors=[
            {"family": "张", "given": "三"},
            {"family": "李", "given": "四"},
            {"family": "王", "given": "五"},
        ],
        journal_name="中国图书馆学报",
        year=2024,
        volume="50",
        issue="2",
        page="100-120",
        issn=["1001-8867"],
        pub_type="article-journal",
    )


@pytest.fixture
def record_en():
    """英文期刊文章，双作者"""
    return ScholarlyRecord(
        doi="10.1234/test.3",
        title="A Survey of Platform Governance Models",
        authors=[
            {"family": "Smith", "given": "John"},
            {"family": "Jones", "given": "Alice B"},
        ],
        journal_name="Journal of Communication Research",
        year=2023,
        volume="40",
        issue="1",
        page="1-25",
        issn=["1005-2577"],
        pub_type="article-journal",
    )


@pytest.fixture
def record_no_volume():
    """缺卷号，有期号和页码"""
    return ScholarlyRecord(
        title="某篇缺卷号的文章",
        authors=[{"family": "张", "given": "三"}],
        journal_name="新闻与传播研究",
        year=2025,
        issue="4",
        page="15-28",
        pub_type="article-journal",
    )


@pytest.fixture
def record_no_issue():
    """缺期号，有卷号和页码"""
    return ScholarlyRecord(
        title="缺期号的文章",
        authors=[{"family": "李", "given": "四"}],
        journal_name="情报学报",
        year=2025,
        volume="30",
        page="50-60",
        pub_type="article-journal",
    )


@pytest.fixture
def record_no_page():
    """缺页码，有卷期"""
    return ScholarlyRecord(
        title="无页码的文章",
        authors=[{"family": "王", "given": "五"}],
        journal_name="新闻与传播研究",
        year=2025,
        volume="32",
        issue="4",
        pub_type="article-journal",
    )


@pytest.fixture
def record_article_number():
    """仅有 article number，无页码"""
    return ScholarlyRecord(
        title="Article with article number",
        authors=[{"family": "Brown", "given": "C"}],
        journal_name="Physical Review Letters",
        year=2024,
        volume="132",
        article_number="012345",
        pub_type="article-journal",
    )


@pytest.fixture
def record_with_doi():
    """含 DOI — DOI 不应出现在 GB/T numeric 输出中"""
    return ScholarlyRecord(
        doi="10.1234/abcdef",
        title="Article With DOI",
        authors=[{"family": "Taylor", "given": "S"}],
        journal_name="Nature",
        year=2025,
        volume="600",
        page="100-110",
        pub_type="article-journal",
    )


@pytest.fixture
def record_mixed_authors():
    """中英文作者混合"""
    return ScholarlyRecord(
        title="Cross-Cultural Study",
        authors=[
            {"family": "张", "given": "三"},
            {"family": "Smith", "given": "John"},
            {"family": "李", "given": "四"},
        ],
        journal_name="International Journal of Communication",
        year=2025,
        volume="15",
        page="1-20",
        pub_type="article-journal",
    )


@pytest.fixture
def record_cn_many_authors():
    """中文期刊文章，超过三位作者（验证"等"截断）"""
    return ScholarlyRecord(
        doi="10.1234/test.cnmany",
        title="大规模语言模型的知识增强方法研究",
        authors=[
            {"family": "张", "given": "三"},
            {"family": "李", "given": "四"},
            {"family": "王", "given": "五"},
            {"family": "赵", "given": "六"},
            {"family": "刘", "given": "七"},
        ],
        journal_name="中国图书馆学报",
        year=2024,
        volume="50",
        issue="3",
        page="50-75",
        issn=["1001-8867"],
        pub_type="article-journal",
    )


@pytest.fixture
def record_en_single():
    """英文期刊文章，单作者"""
    return ScholarlyRecord(
        doi="10.1234/test.ensingle",
        title="Understanding Platform Power Dynamics",
        authors=[{"family": "Johnson", "given": "Michael"}],
        journal_name="Journal of Communication",
        year=2023,
        volume="45",
        issue="2",
        page="200-215",
        issn=["1234-5678"],
        pub_type="article-journal",
    )


@pytest.fixture
def record_en_many_authors():
    """英文期刊文章，超过三位作者（验证 et al 截断）"""
    return ScholarlyRecord(
        doi="10.1234/test.enmany",
        title="Advances in Neural Machine Translation",
        authors=[
            {"family": "Brown", "given": "Alice"},
            {"family": "Davis", "given": "Robert K"},
            {"family": "Wilson", "given": "Elizabeth"},
            {"family": "Taylor", "given": "James"},
        ],
        journal_name="Computational Linguistics",
        year=2025,
        volume="51",
        issue="1",
        page="1-30",
        issn=["0891-2017"],
        pub_type="article-journal",
    )


@pytest.fixture
def record_year_only():
    """仅有年份的文章（缺卷期页码 — 非网络首发，仅数据不完整）"""
    return ScholarlyRecord(
        doi="10.1234/yearonly",
        title="The Future of Digital Governance",
        authors=[{"family": "陈", "given": "小明"}],
        journal_name="新闻与传播研究",
        year=2025,
        pub_type="article-journal",
    )


# ═══════════════════════════════════════════════════════════
# CSL-JSON conversion
# ═══════════════════════════════════════════════════════════

def test_to_csl_json_basic(record_cn_single):
    csl = to_csl_json(record_cn_single)
    assert csl["type"] == "article-journal"
    assert csl["title"] == "平台治理中的算法权力研究"
    assert csl["container-title"] == "新闻与传播研究"
    assert csl["volume"] == "32"
    assert csl["issue"] == "4"
    assert csl["page"] == "15-28"
    assert csl["DOI"] == "10.1234/test.1"
    assert len(csl["author"]) == 1
    assert csl["author"][0]["family"] == "张"
    assert csl["issued"]["date-parts"] == [[2025]]


def test_to_csl_json_no_authors():
    """Record with no authors still produces valid CSL-JSON."""
    record = ScholarlyRecord(title="Title Only", pub_type="article-journal")
    csl = to_csl_json(record)
    assert csl["title"] == "Title Only"
    assert "author" not in csl


# ═══════════════════════════════════════════════════════════
# GB/T 7714-2015 Golden Tests — Numeric (顺序编码制)
#
# Expected strings are HAND-CRAFTED per GB/T 7714-2015 §8.1.1:
#   作者. 题名[J]. 刊名, 年, 卷(期): 页码.
#
# Rules:
#   - ≤3 authors: list all. >3: first 3 + "等" (Chinese) / "et al" (non-CJK).
#   - Journal name and year separated by ", ".
#   - DOI NOT included in numeric output.
#   - Article number substitutes for page when page is absent.
#   - No volume → issue attaches to year: 年(期): 页码.
# ═══════════════════════════════════════════════════════════

class TestGBT7714NumericGolden:
    """Golden tests for GB/T 7714-2015 numeric style (fallback)."""

    def setup_method(self):
        self.fmt = GBT7714FallbackFormatter()

    def test_golden_cn_single(self, record_cn_single):
        """中文单作者: 作者. 题名[J]. 刊名, 年, 卷(期): 页码."""
        cit = self.fmt.format_numeric(record_cn_single)
        expected = "张三. 平台治理中的算法权力研究[J]. 新闻与传播研究, 2025, 32(4): 15-28."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"

    def test_golden_cn_three_authors(self, record_cn_three_authors):
        """中文三作者（≤3，全部照录）."""
        cit = self.fmt.format_numeric(record_cn_three_authors)
        expected = "张三, 李四, 王五. 深度学习在自然语言处理中的应用[J]. 中国图书馆学报, 2024, 50(2): 100-120."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"

    def test_golden_cn_many_authors(self, record_cn_many_authors):
        """中文超过三作者: 前三位 + '等'."""
        cit = self.fmt.format_numeric(record_cn_many_authors)
        expected = "张三, 李四, 王五, 等. 大规模语言模型的知识增强方法研究[J]. 中国图书馆学报, 2024, 50(3): 50-75."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"

    def test_golden_en_single(self, record_en_single):
        """英文单作者: 姓 名缩写. 题名[J]. 刊名, 年, 卷(期): 页码."""
        cit = self.fmt.format_numeric(record_en_single)
        expected = "Johnson M. Understanding Platform Power Dynamics[J]. Journal of Communication, 2023, 45(2): 200-215."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"

    def test_golden_en_two_authors(self, record_en):
        """英文双作者: 用缩写."""
        cit = self.fmt.format_numeric(record_en)
        expected = "Smith J, Jones A B. A Survey of Platform Governance Models[J]. Journal of Communication Research, 2023, 40(1): 1-25."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"

    def test_golden_en_many_authors(self, record_en_many_authors):
        """英文超过三作者: 前三位 + 'et al'."""
        cit = self.fmt.format_numeric(record_en_many_authors)
        expected = "Brown A, Davis R K, Wilson E, et al. Advances in Neural Machine Translation[J]. Computational Linguistics, 2025, 51(1): 1-30."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"

    def test_golden_mixed_authors(self, record_mixed_authors):
        """中英文混合: 各按规则格式化."""
        cit = self.fmt.format_numeric(record_mixed_authors)
        expected = "张三, Smith J, 李四. Cross-Cultural Study[J]. International Journal of Communication, 2025, 15: 1-20."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"

    def test_golden_no_volume(self, record_no_volume):
        """缺卷号: 期号直接接年份 — 年(期): 页码."""
        cit = self.fmt.format_numeric(record_no_volume)
        expected = "张三. 某篇缺卷号的文章[J]. 新闻与传播研究, 2025(4): 15-28."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"

    def test_golden_no_issue(self, record_no_issue):
        """缺期号: 仅卷号 — 年, 卷: 页码."""
        cit = self.fmt.format_numeric(record_no_issue)
        expected = "李四. 缺期号的文章[J]. 情报学报, 2025, 30: 50-60."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"

    def test_golden_no_page(self, record_no_page):
        """缺页码: 不崩溃，以卷期结尾."""
        cit = self.fmt.format_numeric(record_no_page)
        expected = "王五. 无页码的文章[J]. 新闻与传播研究, 2025, 32(4)."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"

    def test_golden_article_number(self, record_article_number):
        """Article number 替代页码."""
        cit = self.fmt.format_numeric(record_article_number)
        expected = "Brown C. Article with article number[J]. Physical Review Letters, 2024, 132: 012345."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"

    def test_golden_with_doi(self, record_with_doi):
        """DOI 存在不影响 GB/T numeric 格式化（标准不要求输出 DOI）."""
        cit = self.fmt.format_numeric(record_with_doi)
        expected = "Taylor S. Article With DOI[J]. Nature, 2025, 600: 100-110."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"
        # DOI should NOT appear in the formatted citation
        assert "10.1234" not in cit.formatted, "DOI should not appear in GB/T numeric output"

    def test_golden_year_only(self, record_year_only):
        """仅年份信息（缺卷/期/页码）: 不崩溃，以年份结尾."""
        cit = self.fmt.format_numeric(record_year_only)
        expected = "陈小明. The Future of Digital Governance[J]. 新闻与传播研究, 2025."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"


# ═══════════════════════════════════════════════════════════
# GB/T 7714-2015 Golden Tests — Author-Date (著者-出版年)
#
# Expected strings are HAND-CRAFTED per GB/T 7714-2015:
#   作者. (年). 题名[J]. 刊名, 卷(期): 页码.
# ═══════════════════════════════════════════════════════════

class TestGBT7714AuthorDateGolden:
    """Golden tests for GB/T 7714-2015 author-date style."""

    def setup_method(self):
        self.fmt = GBT7714FallbackFormatter()

    def test_golden_author_date_cn(self, record_cn_single):
        """Author-date: 年份在著者之后、题名之前."""
        cit = self.fmt.format_author_date(record_cn_single)
        expected = "张三. (2025). 平台治理中的算法权力研究[J]. 新闻与传播研究, 32(4): 15-28."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"

    def test_golden_author_date_en(self, record_en_single):
        """Author-date English: year after author, before title."""
        cit = self.fmt.format_author_date(record_en_single)
        expected = "Johnson M. (2023). Understanding Platform Power Dynamics[J]. Journal of Communication, 45(2): 200-215."
        assert cit.formatted == expected, f"\n  Expected: {expected}\n  Got:      {cit.formatted}"


# ═══════════════════════════════════════════════════════════
# DOI preservation in other formats
# ═══════════════════════════════════════════════════════════

def test_csl_json_preserves_doi(record_with_doi):
    """CSL-JSON MUST include DOI field."""
    csl = to_csl_json(record_with_doi)
    assert csl["DOI"] == "10.1234/abcdef"


def test_bibtex_preserves_doi(record_with_doi):
    """BibTeX MUST include DOI field."""
    cit = export_bibtex(record_with_doi)
    assert "10.1234/abcdef" in cit.formatted
    assert "doi" in cit.formatted.lower()


def test_ris_preserves_doi(record_with_doi):
    """RIS MUST include DOI field."""
    cit = export_ris(record_with_doi)
    assert "DO  - 10.1234/abcdef" in cit.formatted


# ═══════════════════════════════════════════════════════════
# Unsupported types — must return explicit marker, not fake
# ═══════════════════════════════════════════════════════════

def test_unsupported_type_numeric():
    """Non journal-article → [UNSUPPORTED TYPE: ...]."""
    fmt = GBT7714FallbackFormatter()
    record = ScholarlyRecord(
        title="A Book", pub_type="book",
        authors=[{"family": "Author", "given": "Name"}], year=2025,
    )
    cit = fmt.format_numeric(record)
    assert cit.status == SourceStatus.UNAVAILABLE
    assert "UNSUPPORTED" in cit.formatted
    assert "book" in cit.formatted


def test_unsupported_type_author_date():
    """Non journal-article author-date → [UNSUPPORTED TYPE: ...]."""
    fmt = GBT7714FallbackFormatter()
    record = ScholarlyRecord(
        title="A Book", pub_type="book",
        authors=[{"family": "Author", "given": "Name"}], year=2025,
    )
    cit = fmt.format_author_date(record)
    assert cit.status == SourceStatus.UNAVAILABLE
    assert "UNSUPPORTED" in cit.formatted


# ═══════════════════════════════════════════════════════════
# APA 7 format
# ═══════════════════════════════════════════════════════════

def test_apa7_format_cn(record_cn_single):
    fmt = APA7FallbackFormatter()
    cit = fmt.format(record_cn_single)
    assert "(2025)" in cit.formatted
    assert "新闻与传播研究" in cit.formatted


def test_apa7_format_en(record_en):
    fmt = APA7FallbackFormatter()
    cit = fmt.format(record_en)
    assert "Smith" in cit.formatted
    assert "Jones" in cit.formatted
    assert "(2023)" in cit.formatted


# ═══════════════════════════════════════════════════════════
# BibTeX export
# ═══════════════════════════════════════════════════════════

def test_bibtex_export(record_cn_single):
    cit = export_bibtex(record_cn_single)
    assert "@article" in cit.formatted
    assert "平台治理中的算法权力研究" in cit.formatted
    assert "新闻与传播研究" in cit.formatted
    assert "2025" in cit.formatted
    assert cit.style == CitationStyle.BIBTEX


def test_bibtex_cite_key(record_en):
    cit = export_bibtex(record_en)
    assert cit.formatted.startswith("@article{")
    assert "smith" in cit.formatted.lower()


# ═══════════════════════════════════════════════════════════
# RIS export
# ═══════════════════════════════════════════════════════════

def test_ris_export(record_cn_single):
    cit = export_ris(record_cn_single)
    assert "TY  - JOUR" in cit.formatted
    assert "TI  - 平台治理中的算法权力研究" in cit.formatted
    assert "AU  - 三 张" in cit.formatted  # RIS: given family
    assert "DO  - 10.1234/test.1" in cit.formatted
    assert "ER  - " in cit.formatted
    assert cit.style == CitationStyle.RIS


# ═══════════════════════════════════════════════════════════
# CitationFormatter (top-level) — format_all
# ═══════════════════════════════════════════════════════════

def test_formatter_format_all(record_cn_single):
    fmt = CitationFormatter()
    results = fmt.format_all(record_cn_single)
    assert len(results) == 5
    styles = {r.style for r in results}
    assert CitationStyle.GBT7714_NUMERIC in styles
    assert CitationStyle.GBT7714_AUTHOR_DATE in styles
    assert CitationStyle.BIBTEX in styles
    assert CitationStyle.RIS in styles


def test_formatter_specific_style(record_en):
    fmt = CitationFormatter()
    cit = fmt.format(record_en, CitationStyle.APA7)
    assert cit.style == CitationStyle.APA7
    assert cit.formatted


# ═══════════════════════════════════════════════════════════
# Engine Selection Tests (Phase 1A.2 micro-fix)
# ═══════════════════════════════════════════════════════════

class TestEngineSelection:
    """Verify that CitationFormatter routes to the correct engine."""

    def test_auto_gbt_journal_uses_fallback(self, record_cn_single):
        """AUTO + GB/T journal article → fallback, even with citeproc installed."""
        fmt = CitationFormatter(engine=CitationEngine.AUTO)
        cit = fmt.format(record_cn_single, CitationStyle.GBT7714_NUMERIC)
        assert cit.engine_used == "fallback", (
            f"Expected 'fallback', got '{cit.engine_used}'"
        )
        assert cit.strict is True
        assert "UNSUPPORTED" not in cit.formatted

    def test_auto_apa_uses_citeproc_when_available(self, record_en):
        """AUTO + APA → citeproc when available; UNAVAILABLE when not installed."""
        fmt = CitationFormatter(engine=CitationEngine.AUTO)
        cit = fmt.format(record_en, CitationStyle.APA7)
        if HAS_CITEPROC:
            assert cit.engine_used == "citeproc", (
                f"Expected 'citeproc', got '{cit.engine_used}'"
            )
            assert cit.strict is True
        else:
            # Without citeproc → UNAVAILABLE, no silent fallback to unvalidated formatter
            assert cit.engine_used == "", (
                f"Expected empty engine_used (unavailable), got '{cit.engine_used}'"
            )
            assert cit.status == SourceStatus.UNAVAILABLE
            assert cit.strict is False
            assert any("no validated APA fallback" in w for w in cit.warnings)

    def test_force_fallback_journal_article(self, record_cn_single):
        """FALLBACK mode + journal article → fallback."""
        fmt = CitationFormatter(engine=CitationEngine.FALLBACK)
        cit = fmt.format(record_cn_single, CitationStyle.GBT7714_NUMERIC)
        assert cit.engine_used == "fallback"
        assert cit.strict is True
        assert "UNSUPPORTED" not in cit.formatted

    def test_force_fallback_book_returns_unsupported(self):
        """FALLBACK mode + unsupported type → UNSUPPORTED, no citeproc escape."""
        fmt = CitationFormatter(engine=CitationEngine.FALLBACK)
        record = ScholarlyRecord(
            title="A Book", pub_type="book",
            authors=[{"family": "Author", "given": "Name"}], year=2025,
        )
        cit = fmt.format(record, CitationStyle.GBT7714_NUMERIC)
        assert cit.engine_used == "fallback"
        assert "UNSUPPORTED" in cit.formatted
        assert cit.status == SourceStatus.UNAVAILABLE

    def test_force_citeproc_journal_article(self, record_cn_single):
        """CITEPROC mode + journal article → citeproc with strict=False."""
        if not HAS_CITEPROC:
            pytest.skip("citeproc-py not installed")
        fmt = CitationFormatter(engine=CitationEngine.CITEPROC)
        cit = fmt.format(record_cn_single, CitationStyle.GBT7714_NUMERIC)
        assert cit.engine_used == "citeproc"
        assert cit.strict is False, "GB/T via citeproc must be strict=False"
        assert any("locale" in w or "name-format" in w for w in cit.warnings), (
            f"Expected locale/name-format warning, got: {cit.warnings}"
        )
        assert cit.status == SourceStatus.AVAILABLE

    def test_force_citeproc_failure_no_silent_fallback(self):
        """CITEPROC mode + failure → ERROR, no silent fallback."""
        if not HAS_CITEPROC:
            # Without citeproc, forced citeproc → ERROR
            fmt = CitationFormatter(engine=CitationEngine.CITEPROC)
            record = ScholarlyRecord(
                title="Test", pub_type="article-journal",
                authors=[{"family": "张", "given": "三"}],
                journal_name="测试", year=2025,
            )
            cit = fmt.format(record, CitationStyle.GBT7714_NUMERIC)
            assert cit.engine_used == "citeproc"
            assert cit.status == SourceStatus.ERROR
            assert "UNAVAILABLE" in cit.formatted or "not installed" in cit.formatted
        else:
            # With citeproc, simulate a book (unsupported type via citeproc)
            fmt = CitationFormatter(engine=CitationEngine.CITEPROC)
            record = ScholarlyRecord(
                title="A Book", pub_type="book",
                authors=[{"family": "Author", "given": "Name"}], year=2025,
            )
            cit = fmt.format(record, CitationStyle.GBT7714_NUMERIC)
            assert cit.engine_used == "citeproc"
            # CiteprocFormatter rejects non-journal types → UNSUPPORTED → ERROR status
            if cit.status == SourceStatus.ERROR:
                assert "UNSUPPORTED" in cit.formatted or "CITEPROC" in cit.formatted
            # Either way, must not be fallback output
            assert cit.engine_used == "citeproc"

    def test_auto_apa_citeproc_success(self, record_en):
        """AUTO + APA + citeproc installed → citeproc (strict=True, no warnings)."""
        if not HAS_CITEPROC:
            pytest.skip("citeproc-py not installed")
        fmt = CitationFormatter(engine=CitationEngine.AUTO)
        cit = fmt.format(record_en, CitationStyle.APA7)
        assert cit.engine_used == "citeproc", (
            f"Expected 'citeproc', got '{cit.engine_used}'"
        )
        assert cit.strict is True
        assert cit.warnings == []
        assert cit.status == SourceStatus.AVAILABLE

    def test_auto_apa_citeproc_unavailable_no_fallback(self, record_en):
        """AUTO + APA + citeproc NOT installed → UNAVAILABLE, does NOT call fallback."""
        import scholarly.citation_formatter as cf
        orig = cf.HAS_CITEPROC
        cf.HAS_CITEPROC = False
        try:
            fmt = cf.CitationFormatter(engine=cf.CitationEngine.AUTO)
            cit = fmt.format(record_en, cf.CitationStyle.APA7)
            assert cit.engine_used == "", (
                f"Expected empty engine_used, got '{cit.engine_used}'"
            )
            assert cit.status == SourceStatus.UNAVAILABLE
            assert cit.strict is False
            assert any("no validated APA fallback" in w for w in cit.warnings), (
                f"Expected 'no validated APA fallback' in warnings, got: {cit.warnings}"
            )
            assert "CITEPROC REQUIRED" in cit.formatted
        finally:
            cf.HAS_CITEPROC = orig

    def test_auto_apa_citeproc_failure_no_fallback(self, record_en):
        """AUTO + APA + citeproc formatting raises → ERROR, no silent fallback."""
        if not HAS_CITEPROC:
            pytest.skip("citeproc-py not installed")
        fmt = CitationFormatter(engine=CitationEngine.AUTO)
        # Simulate citeproc formatter returning an error
        original = fmt._citeproc_fmt.format_apa
        fmt._citeproc_fmt.format_apa = lambda r: CitationData(
            style=CitationStyle.APA7,
            formatted="[CITEPROC ERROR: simulated failure]",
            status=SourceStatus.ERROR,
        )
        try:
            cit = fmt.format(record_en, CitationStyle.APA7)
            assert cit.engine_used == "citeproc", (
                f"Expected 'citeproc', got '{cit.engine_used}'"
            )
            assert cit.status == SourceStatus.ERROR
            assert "CITEPROC ERROR" in cit.formatted
            assert cit.strict is False
            assert any("failed to produce valid" in w for w in cit.warnings), (
                f"Expected failure warning, got: {cit.warnings}"
            )
        finally:
            fmt._citeproc_fmt.format_apa = original

    def test_fallback_apa_unsupported(self, record_en):
        """FALLBACK + APA → UNSUPPORTED with clear warning."""
        fmt = CitationFormatter(engine=CitationEngine.FALLBACK)
        cit = fmt.format(record_en, CitationStyle.APA7)
        assert cit.engine_used == "fallback", (
            f"Expected 'fallback', got '{cit.engine_used}'"
        )
        assert cit.status == SourceStatus.UNAVAILABLE
        assert cit.strict is False
        assert any("validated GB/T 7714" in w for w in cit.warnings), (
            f"Expected 'validated GB/T 7714' in warnings, got: {cit.warnings}"
        )
        assert "UNSUPPORTED" in cit.formatted

    def test_citeproc_apa_unavailable(self, record_en):
        """CITEPROC + APA + citeproc not installed → ERROR."""
        import scholarly.citation_formatter as cf
        orig = cf.HAS_CITEPROC
        cf.HAS_CITEPROC = False
        try:
            fmt = cf.CitationFormatter(engine=cf.CitationEngine.CITEPROC)
            cit = fmt.format(record_en, cf.CitationStyle.APA7)
            assert cit.engine_used == "citeproc", (
                f"Expected 'citeproc', got '{cit.engine_used}'"
            )
            assert cit.status == SourceStatus.ERROR
            assert "not installed" in cit.formatted
        finally:
            cf.HAS_CITEPROC = orig

    def test_citeproc_apa_failure(self, record_en):
        """CITEPROC + APA + formatting failure → ERROR."""
        if not HAS_CITEPROC:
            pytest.skip("citeproc-py not installed")
        fmt = CitationFormatter(engine=CitationEngine.CITEPROC)
        original = fmt._citeproc_fmt.format_apa
        fmt._citeproc_fmt.format_apa = lambda r: CitationData(
            style=CitationStyle.APA7,
            formatted="[CITEPROC ERROR: simulated failure]",
            status=SourceStatus.ERROR,
        )
        try:
            cit = fmt.format(record_en, CitationStyle.APA7)
            assert cit.engine_used == "citeproc", (
                f"Expected 'citeproc', got '{cit.engine_used}'"
            )
            assert cit.status == SourceStatus.ERROR
            assert "CITEPROC ERROR" in cit.formatted
        finally:
            fmt._citeproc_fmt.format_apa = original

    def test_direct_paths_unaffected_by_engine(self, record_cn_single):
        """BibTeX and RIS always use 'direct' engine regardless of citation_engine."""
        for engine in (CitationEngine.AUTO, CitationEngine.FALLBACK, CitationEngine.CITEPROC):
            fmt = CitationFormatter(engine=engine)

            bib = fmt.format(record_cn_single, CitationStyle.BIBTEX)
            assert bib.engine_used == "direct", (
                f"BibTeX with {engine.value}: expected 'direct', got '{bib.engine_used}'"
            )
            assert bib.status == SourceStatus.AVAILABLE
            assert "10.1234/test.1" in bib.formatted  # DOI preserved

            ris = fmt.format(record_cn_single, CitationStyle.RIS)
            assert ris.engine_used == "direct", (
                f"RIS with {engine.value}: expected 'direct', got '{ris.engine_used}'"
            )
            assert ris.status == SourceStatus.AVAILABLE
            assert "DO  - 10.1234/test.1" in ris.formatted  # DOI preserved


# ═══════════════════════════════════════════════════════════
# citeproc-py availability check
# ═══════════════════════════════════════════════════════════

def test_citeproc_availability_documented():
    """HAS_CITEPROC is a boolean; CITEPROC_VERSION is a string."""
    assert isinstance(HAS_CITEPROC, bool)
    assert isinstance(CITEPROC_VERSION, str)
    print(f"\n  citeproc-py: {'available' if HAS_CITEPROC else 'NOT installed'} ({CITEPROC_VERSION})")


def test_fallback_works_without_citeproc():
    """Fallback formatter produces valid citations without citeproc-py."""
    record = ScholarlyRecord(
        title="Test Article",
        authors=[{"family": "张", "given": "三"}],
        journal_name="新闻与传播研究",
        year=2025, volume="32", issue="4", page="15-28",
        pub_type="article-journal",
    )
    fmt = GBT7714FallbackFormatter()
    cit = fmt.format_numeric(record)
    assert cit.formatted
    assert "UNSUPPORTED" not in cit.formatted
